### ISSUE TITLE
Firefox extension in InPrivate doesn't have the config

### ISSUE THREAD

**Issue by etec-masterofsynapse** [linkwarden/browser-extension#60] opened 2024-02-11 22:47 UTC
Extension has been configured in regular Firefox.
Open an InPrivate session and extension wants to be set up again.
Run through the config again, it works for this session.
Close the session and open a new one, extension wants initial config again.

**Comment by crkos** [comment] 2024-02-11 23:41
Can you tell which branch are you using currently, or the one from store?.

Does this happens when using a regular session?.

**Comment by crkos** [comment] 2024-02-11 23:43
The most likely thing happening is that the nature of InPrivate which doesnt store data after is closed. unless you are saying that it needs to be configured again once the session in private is closed

**Comment by etec-masterofsynapse** [comment] 2024-02-12 17:02
@crkos 
I am running the version from the Mozilla Store.
It doesn't happen in a regular session.

And yes, it wants to do the initial config everytime you open an InPrivate window, not just the first time.

**Comment by crkos** [comment] 2024-02-12 17:11
I'm actually quite limited in this regard take a look at:

https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API

Since firefox implementation doesnt have chrome.storage like apis i can't do much.

This is by design, read specifically: [Private Browsing / Incognito modes](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API#private_browsing_incognito_modes)

**Comment by etec-masterofsynapse** [comment] 2024-02-12 17:16
> I'm actually quite limited in this regard take a look at:
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API
> 
> Since firefox implementation doesnt have chrome.storage like apis i can't do much.
> 
> This is by design, read specifically: [Private Browsing / Incognito modes](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API#private_browsing_incognito_modes)

If this is by design, how come EVERY other extension is able to have its settings saved across InPrivate and regular?
I just enable "Allow to run in InPrivate" and everything just works.
This (LinkWarden) is the first extension I have this problem with.

**Comment by crkos** [comment] 2024-02-12 17:21
I've read a little bit more, it seems that browser.storage.local behaves like chrome.storage, It seems that indeed i'm using the window.localStorage incorrectly, it is advised on the doc for web extension to not use this api, but the browser api. So i will just change that,

**Comment by crkos** [comment] 2024-02-12 17:45
Ok i solved on:  4ea36b8

**Comment by crkos** [comment] 2024-02-12 17:46
Tested on private instance of firefox

**Comment by etec-masterofsynapse** [comment] 2024-02-12 20:24
@crkos 
Thanks, when will the version in the store be updated?

**Comment by crkos** [comment] 2024-02-13 16:44
I'm waiting on Daniel to push the next version of linkwarden because it will include api keys so authentication will be less of a hassle

**Comment by daniel31x13** [comment] 2024-02-13 19:15
@etec-masterofsynapse yep, it's my fault. The next release is something big, batch editing/deletion, api keys, PWA support, sub-collections and more...

It'll probably be ready by the end of this week or early next week.

Also @crkos sorry for the delay...

**Comment by crkos** [comment] 2024-02-13 20:03
It's ok actually, even if it was ready by today, I can't work on it right now, Maybe in 2-3 weeks from now im a little bit more free

**Comment by crkos** [comment] 2024-04-21 05:35
Fixed on last update.

**Closed by crkos** 2024-04-21 05:35 UTC
